import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  items: [
    {
      id: 1,
      name: "Artichoke Hearts",
      price: 3.99,
      unit: "can",
      image: "artichoke-hearts.PNG",
      category: "Canned Goods",
    },
    {
      id: 2,
      name: "Peas and Carrots",
      price: 2.49,
      unit: "can",
      image: "peas-and-carrots.PNG",
      category: "Canned Goods",
    },
    {
      id: 3,
      name: "Tomato Basil",
      price: 4.99,
      unit: "can",
      image: "tomato-basil-soup.PNG",
      category: "Soup",
    },
    {
      id: 4,
      name: "Lentil Soup",
      price: 2.99,
      unit: "bag",
      image: "lentil-soup.PNG",
      category: "Soups",
    },
    {
      id: 5,
      name: "Sushi Rice",
      price: 5.99,
      unit: "bag",
      image: "sushi-rice.PNG",
      category: "Grains",
    },
    {
      id: 6,
      name: "Wild Rice",
      price: 6.99,
      unit: "bag",
      image: "wild-rice.PNG",
      category: "Grains",
    },
    {
      id: 7,
      name: "Cacio e Pepe Sauce",
      price: 3.99,
      unit: "jar",
      image: "cacio-e-pepe-sauce.PNG",
      category: "Pasta Sauce",
    },
    {
      id: 8,
      name: "Potato Gnocchi",
      price: 4.99,
      unit: "package",
      image: "potato-gnocchi.PNG",
      category: "Pasta",
    },
    {
      id: 9,
      name: "Slider Buns",
      price: 3.49,
      unit: "bag",
      image: "slider-buns.PNG",
      category: "Bread",
    },
    {
      id: 10,
      name: "Key Lime Pie",
      price: 8.99,
      unit: "pie",
      image: "key-lime-pie.PNG",
      category: "Bakery",
    },
    {
      id: 11,
      name: "Macaroons",
      price: 5.99,
      unit: "box",
      image: "macaroons.PNG",
      category: "Bakery",
    },
    {
      id: 12,
      name: "Raspberry Tart",
      price: 6.99,
      unit: "tart",
      image: "raspberry-tart.PNG",
      category: "Bakery",
    },
    {
      id: 13,
      name: "Blueberry Tart",
      price: 6.99,
      unit: "tart",
      image: "blueberry-tart.PNG",
      category: "Bakery",
    },
    {
      id: 14,
      name: "Blackberry Tart",
      price: 6.99,
      unit: "tart",
      image: "blackberry-tart.PNG",
      category: "Bakery",
    },
    {
      id: 15,
      name: "Cherry Tart",
      price: 6.99,
      unit: "tart",
      image: "cherry-tart.PNG",
      category: "Bakery",
    },
    {
      id: 16,
      name: "Custom Cake",
      price: 24.99,
      unit: "cake",
      image: "custom-cake.PNG",
      category: "Bakery",
    },
    {
      id: 17,
      name: "Capicola",
      price: 7.99,
      unit: "package",
      image: "capicola.PNG",
      category: "Deli",
    },
    {
      id: 18,
      name: "Soppressata",
      price: 8.99,
      unit: "package",
      image: "soppressata.PNG",
      category: "Deli",
    },
    {
      id: 19,
      name: "Baba Ganoush",
      price: 4.99,
      unit: "container",
      image: "baba-ganoush.PNG",
      category: "Dips",
    },
    {
      id: 20,
      name: "Mild Salsa",
      price: 3.99,
      unit: "jar",
      image: "mild-salsa.PNG",
      category: "Dips",
    },
    {
      id: 21,
      name: "Spicy Salsa",
      price: 3.99,
      unit: "jar",
      image: "spicy-salsa.PNG",
      category: "Dips",
    },
    {
      id: 22,
      name: "Hazelnut Spread",
      price: 5.99,
      unit: "jar",
      image: "hazelnut-spread.PNG",
      category: "Spreads",
    },
    {
      id: 23,
      name: "Horseradish Sauce",
      price: 3.49,
      unit: "jar",
      image: "horseradish-sauce.PNG",
      category: "Condiments",
    },
    {
      id: 24,
      name: "Lemon Aioli",
      price: 4.99,
      unit: "jar",
      image: "lemon-aioli.PNG",
      category: "Condiments",
    },
    {
      id: 25,
      name: "Dijon Mustard",
      price: 3.49,
      unit: "bottle",
      image: "dijon-mustard.PNG",
      category: "Condiments",
    },
    {
      id: 26,
      name: "Beef Teriyaki Stir Fry",
      price: 8.99,
      unit: "package",
      image: "beef-teriyaki.PNG",
      category: "Frozen Meals",
    },
    {
      id: 27,
      name: "Chicken Teriyaki Stir Fry",
      price: 7.99,
      unit: "package",
      image: "chicken-teriyaki.PNG",
      category: "Frozen Meals",
    },
    {
      id: 28,
      name: "Veggie Stir Fry",
      price: 6.99,
      unit: "package",
      image: "veggie-stir-fry.PNG",
      category: "Frozen Meals",
    },
    {
      id: 29,
      name: "Saltine Crackers",
      price: 2.99,
      unit: "box",
      image: "saltine-crackers.PNG",
      category: "Crackers",
    },
    {
      id: 30,
      name: "Round Tortilla Chips",
      price: 1.99,
      unit: "ear",
      image: "round-tortilla-chips.PNG",
      category: "Chips",
    },
    {
      id: 31,
      name: "Mini Chocolate Chip Cookies",
      price: 4.99,
      unit: "bag",
      image: "mini-cookies.PNG",
      category: "Snacks",
    },
    {
      id: 32,
      name: "Animal Crackers",
      price: 3.49,
      unit: "bag",
      image: "animal-crackers.PNG",
      category: "Snacks",
    },
    {
      id: 33,
      name: "Salt Water Taffy",
      price: 5.99,
      unit: "box",
      image: "salt-water-taffy.PNG",
      category: "Candy",
    },
    {
      id: 34,
      name: "Granola Bars",
      price: 3.99,
      unit: "box",
      image: "granola-bars.PNG",
      category: "Breakfast",
    },
    {
      id: 35,
      name: "Corn Flakes",
      price: 3.49,
      unit: "box",
      image: "corn-flakes.PNG",
      category: "Cereal",
    },
    {
      id: 36,
      name: "Frosted Corn Flakes",
      price: 3.99,
      unit: "box",
      image: "frosted-corn-flakes.PNG",
      category: "Cereal",
    },
    {
      id: 37,
      name: "Avocado Oil",
      price: 8.99,
      unit: "bottle",
      image: "avocado-oil.PNG",
      category: "Oils",
    },
    {
      id: 38,
      name: "Black Peppercorn",
      price: 4.99,
      unit: "jar",
      image: "black-peppercorn.PNG",
      category: "Spices",
    },
    {
      id: 39,
      name: "White Peppercorn",
      price: 4.99,
      unit: "jar",
      image: "white-peppercorn.PNG",
      category: "Spices",
    },
    {
      id: 40,
      name: "Pink Peppercorn",
      price: 5.99,
      unit: "jar",
      image: "pink-peppercorn.PNG",
      category: "Spices",
    },
    {
      id: 41,
      name: "Green Peppercorn",
      price: 4.99,
      unit: "jar",
      image: "green-peppercorn.PNG",
      category: "Spices",
    },
    {
      id: 42,
      name: "Aji Amarillo Powder",
      price: 5.99,
      unit: "jar",
      image: "aji-amarillo-powder.PNG",
      category: "Spices",
    },
    {
      id: 43,
      name: "Orange Dreamsicle",
      price: 4.99,
      unit: "box",
      image: "orange-dreamsicle.PNG",
      category: "Frozen Desserts",
    },
    {
      id: 44,
      name: "Chocolate Dipped Ice Cream Bar",
      price: 5.99,
      unit: "box",
      image: "strawberry-ice-cream-bar.PNG",
      category: "Frozen Desserts",
    },
    {
      id: 45,
      name: "Chocolate Dipped Ice Cream Bar",
      price: 5.99,
      unit: "box",
      image: "vanilla-ice-cream-bar.PNG",
      category: "Frozen Desserts",
    },
    {
      id: 46,
      name: "Pizza Dough",
      price: 9.99,
      unit: "bag",
      image: "pizza-dough.PNG",
      category: "Frozen",
    },
    {
      id: 47,
      name: "Frozen Fish Nuggets",
      price: 6.99,
      unit: "bag",
      image: "frozen-fish-nuggets.PNG",
      category: "Frozen",
    },
    {
      id: 48,
      name: "Frozen Veggie Spring Rolls",
      price: 4.99,
      unit: "package",
      image: "veggie-spring-rolls.PNG",
      category: "Frozen",
    },
    {
      id: 49,
      name: "Frozen Chicken Spring Rolls",
      price: 5.99,
      unit: "package",
      image: "chicken-spring-rolls.PNG",
      category: "Frozen",
    },
    {
      id: 50,
      name: "Frozen Meatballs",
      price: 7.99,
      unit: "bag",
      image: "frozen-meatballs.PNG",
      category: "Frozen",
    },
    {
      id: 51,
      name: "Frozen Mixed Berries",
      price: 4.99,
      unit: "bag",
      image: "frozen-mixed-berries.PNG",
      category: "Frozen",
    },
    {
      id: 52,
      name: "Frozen Broccoli",
      price: 2.99,
      unit: "bag",
      image: "frozen-broccoli.PNG",
      category: "Frozen",
    },
    {
      id: 53,
      name: "Gluten-Free Chicken Nuggets",
      price: 7.99,
      unit: "bag",
      image: "g-chicken-nuggets.PNG",
      category: "Gluten-Free",
    },
    {
      id: 54,
      name: "Gluten-Free Chicken Tenders",
      price: 8.99,
      unit: "bag",
      image: "gf-chicken-tenders.PNG",
      category: "Gluten-Free",
    },
    {
      id: 55,
      name: "Gluten-Free Chicken Pot Pie",
      price: 6.99,
      unit: "pie",
      image: "gf-chicken-pot-pie.PNG",
      category: "Gluten-Free",
    },
    {
      id: 56,
      name: "Gluten-Free Hot Dog Buns",
      price: 4.99,
      unit: "bag",
      image: "gf-hot-dog-buns.PNG",
      category: "Gluten-Free",
    },
    {
      id: 57,
      name: "Gluten-Free Burger Buns",
      price: 4.99,
      unit: "bag",
      image: "gf-burger-buns.PNG",
      category: "Gluten-Free",
    },
    {
      id: 58,
      name: "Vegan Chocolate Bar",
      price: 4.99,
      unit: "bar",
      image: "vegan-chocolate-bar.PNG",
      category: "Vegan",
    },
    {
      id: 59,
      name: "Vegan Dark Chocolate Bar",
      price: 4.99,
      unit: "bar",
      image: "vegan-dark-chocolate-bar.PNG",
      category: "Vegan",
    },
    {
      id: 60,
      name: "Vegan Mint Chocolate Protein Bar",
      price: 4.99,
      unit: "bar",
      image: "vegan-mint-chocolate-protein-bar.PNG",
      category: "Vegan",
    },
    {
      id: 61,
      name: "Vegan Meat Lovers Pizza",
      price: 8.99,
      unit: "pizza",
      image: "vegan-meat-lovers-pizza.PNG",
      category: "Vegan",
    },
    {
      id: 62,
      name: "Vegan Supreme Pizza",
      price: 8.99,
      unit: "pizza",
      image: "vegan-supreme-pizza.PNG",
      category: "Vegan",
    },
    {
      id: 63,
      name: "Vegan Spinach Artichoke Pizza",
      price: 8.99,
      unit: "pizza",
      image: "vegan-spinach-artichoke-pizza.PNG",
      category: "Vegan",
    },
    {
      id: 64,
      name: "Rice Milk",
      price: 3.99,
      unit: "carton",
      image: "rice-milk.PNG",
      category: "Dairy Alternatives",
    },
    {
      id: 65,
      name: "Almond Milk",
      price: 3.99,
      unit: "carton",
      image: "almond-milk.PNG",
      category: "Dairy Alternatives",
    },
    {
      id: 66,
      name: "Cashew Milk",
      price: 3.99,
      unit: "carton",
      image: "cashew-milk.PNG",
      category: "Dairy Alternatives",
    },
    {
      id: 67,
      name: "Blue Cheese",
      price: 5.99,
      unit: "wedge",
      image: "blue-cheese.PNG",
      category: "Cheese",
    },
    {
      id: 68,
      name: "Colby Jack Cheese Slices",
      price: 4.99,
      unit: "package",
      image: "colby-jack-slices.PNG",
      category: "Cheese",
    },
    {
      id: 69,
      name: "Monterrey Jack Cheese Slices",
      price: 4.99,
      unit: "package",
      image: "monterrey-jack-slices.PNG",
      category: "Cheese",
    },
    {
      id: 70,
      name: "Mozzarella Cheese Slices",
      price: 4.99,
      unit: "package",
      image: "mozzarella-slices.PNG",
      category: "Cheese",
    },
    {
      id: 71,
      name: "Pepper Jack Cheese Slices",
      price: 4.99,
      unit: "package",
      image: "pepper-jack-slices.PNG",
      category: "Cheese",
    },
    {
      id: 72,
      name: "Mild Cheddar Cheese Slices",
      price: 4.99,
      unit: "package",
      image: "mild-cheddar-slices.PNG",
      category: "Cheese",
    },
    {
      id: 73,
      name: "Sharp Cheddar Cheese Slices",
      price: 4.99,
      unit: "package",
      image: "sharp-cheddar-slices.PNG",
      category: "Cheese",
    },
    {
      id: 74,
      name: "Ramune",
      price: 2.99,
      unit: "bottle",
      image: "ramune.PNG",
      category: "Beverages",
    },
    {
      id: 75,
      name: "Strawberry Ramune",
      price: 2.99,
      unit: "bottle",
      image: "strawberry-ramune.PNG",
      category: "Beverages",
    },
    {
      id: 76,
      name: "Melon Ramune",
      price: 2.99,
      unit: "bottle",
      image: "melon-ramune.PNG",
      category: "Beverages",
    },
    {
      id: 77,
      name: "Grape Ramune",
      price: 2.99,
      unit: "bottle",
      image: "grape-ramune.PNG",
      category: "Beverages",
    },
    {
      id: 78,
      name: "Peach Ramune",
      price: 2.99,
      unit: "bottle",
      image: "peach-ramune.PNG",
      category: "Beverages",
    },
    {
      id: 79,
      name: "Lychee Ramune",
      price: 2.99,
      unit: "bottle",
      image: "lychee-ramune.PNG",
      category: "Beverages",
    },
    {
      id: 80,
      name: "Orange Ramune",
      price: 2.99,
      unit: "bottle",
      image: "orange-ramune.PNG",
      category: "Beverages",
    },
    {
      id: 81,
      name: "Mixed Greens Juice",
      price: 4.99,
      unit: "bottle",
      image: "mixed-greens-juice.PNG",
      category: "Juices",
    },
    {
      id: 82,
      name: "Blood Orange Soda",
      price: 2.99,
      unit: "bottle",
      image: "blood-orange-soda.PNG",
      category: "Beverages",
    },
    {
      id: 83,
      name: "Ginger",
      price: 2.99,
      unit: "root",
      image: "ginger.PNG",
      category: "Produce",
    },
    {
      id: 84,
      name: "Spinach and Kale Mix",
      price: 3.99,
      unit: "bag",
      image: "spinach-kale-mix.PNG",
      category: "Produce",
    },
    {
      id: 85,
      name: "Celery",
      price: 2.49,
      unit: "bunch",
      image: "celery.PNG",
      category: "Produce",
    },
    {
      id: 86,
      name: "Peach",
      price: 1.99,
      unit: "each",
      image: "peach.PNG",
      category: "Produce",
    },
    {
      id: 87,
      name: "Grapefruit",
      price: 1.49,
      unit: "each",
      image: "grapefruit.PNG",
      category: "Produce",
    },
    {
      id: 88,
      name: "Raspberries",
      price: 3.99,
      unit: "container",
      image: "raspberries.PNG",
      category: "Produce",
    },
    {
      id: 89,
      name: "Mussels",
      price: 8.99,
      unit: "pound",
      image: "mussels.PNG",
      category: "Seafood",
    },
    {
      id: 90,
      name: "Halibut",
      price: 12.99,
      unit: "pound",
      image: "halibut.PNG",
      category: "Seafood",
    },
  ],
  loading: false,
  error: null,
};

export const saleSlice = createSlice({
  name: "sale",
  initialState,
  reducers: {
    setSaleItems: (state, action) => {
      state.items = action.payload;
    },
    setLoading: (state, action) => {
      state.loading = action.payload;
    },
    setError: (state, action) => {
      state.error = action.payload;
    },
  },
});

export const { setSaleItems, setLoading, setError } = saleSlice.actions;
export default saleSlice.reducer;
